### PR TITLE
fix: resolve destination when bucket is specified in configuration, but destination is not

### PR DESCRIPTION
**Pull request by odinuv**
apparently I was too hotheaded in https://github.com/keboola/output-mapping/pull/72/files

https://keboola.atlassian.net/browse/PS-1663

### CODE REVIEW

**Review by MiroCillik — APPROVED** [review]
lgtm

**Comment by MiroCillik** [comment]
Ked vravis ze ten `else` neni potreba, pretoze manifest je v tomto pripade povinny, tak by to malo byt ok
https://github.com/keboola/output-mapping/pull/72/files#diff-238560ed1c53dd548cdcb8705bc8138d60842fad65a686b235186549c6fefc21L123

**Comment by odinuv** [comment]
Jo ten else byl v každým případě nefunkční https://keboola.atlassian.net/browse/PS-1648

**Comment by MiroCillik** [comment]
Haha, ok :)

**Pull request merged**
