### PR TITLE
PS-1517 ABS files output mapping

### PR DESCRIPTION
**Pull request by pivnicek**
I think we could do as complete a rewriting as we want to here ,  not sure where to draw the line, but they draw themselves somehow

### CODE REVIEW

**Comment by odinuv** [comment]
Summary of changes done in this PR:

- changed adapter so as not to touch the file system -> readFromFile->deserialize
- writeToFile method deleted, was not used
- getContents simplified (line 166 made no sense) and moved to FileWriter
- added workspace provider to AbstractWriter because it is now common to both FileWriter and TableWriter
- added AbsWorkspace file strategy
- reimplmented Local file strategy to the StrategyInterface
- added StrategyFactory + StrategyInterface + AbstractFileStrategy 
- FileWriter - moved file system operations to the strategy classes - added FileItem as a replacement for SplFileInfo
- uploadFiles - added storage type parameter
- TableWriter - use the modified Adapter - file system operations moved from adapter to readTableManifest 
- TableWriter - removed constants duplicating those in input mapping
- TableWriter - removed workspaceprovider - now declared in abstractwriter
- New tests

**Comment by pivnicek** [comment]
holy shit, I knew something like this was happening when it got quiet 😂 .  amazing odin

**Comment by odinuv** [comment]
Also to describe what the actual change is: files can now be read from ABS workspace (splitting file upload code into local and ABS workspace strategy) including *their manifests* (<- that's the big change). Since the file can't be read directly into storage, they're copied to local drive first (handled in `uploadFile()` method of the ABS strategy).

**Review by MiroCillik — APPROVED** [review]
Pride mi to velmi pekne, nic mi neudrelo do oci 🤜 👀  takze 👍

**Comment by odinuv** [comment]
Jeden problem tam je a souvisi to s timhle https://keboola.atlassian.net/browse/PS-1599, takze nez se to mergne tak je potreba upravit IM

**Review by MiroCillik — APPROVED** [review]
lgtm

**Pull request merged**
